### ISSUE TITLE
6.1.1 DB pod known issue clarification

### ISSUE THREAD

**Issue by aboje** [purestorage/pso-csi#163]
Can you clarify this known issue from the 6.1.1 changelog:
"Database volume is mounted as read-only and result in CrashLoopBackOff status of a db pod."

When does that occur and will that put PSO's overall state in jeopardy?

**Comment by dsupure** [comment]
Hi @aboje: 
It won't affect PSO's health as long as your PSO DB service meets the quorum, minimum 3 DB replicas.  One or two db pods in CrashLoopBackOff status is fine. 

We saw the issue from one of our customers. Their environment had a TCP/iSCSI glitch that corrupted the filesystem used by the db. The OS will mount the corrupted filesystem as `read-only` to protect against further damages. However, the pod will turn into `CrashLoopBackOff` status because our cockroach db cannot write the data to the volume anymore.
 
Our cockroach-operator monitors the health of all db pods. It will replace the pod and its db volume when the status is not healthy. So `CrashLoopBackOff` should go away after 20 mins. 

Hope it helps.

**Comment by aboje** [comment]
That's great, thanks for the response.
