### ISSUE TITLE
clusterID characters allowed

### ISSUE THREAD

**Issue by aboje** [purestorage/pso-csi#164]
The values.yaml states that clusterID allows "alphanumeric and underscores".

In PSO5 our namespace.pure value is "pure-csi". We are forced to re-use that value in the clusterID field. 

Will the dash in "pure-csi" cause any problems?

**Comment by aboje** [comment]
Here is the output from a dry-run install:

$ helm install pure-pso pure/pure-pso --version 6.1.1 --namespace default -f pure-pso/values.yaml --dry-run --debug
install.go:159: [debug] Original chart version: "6.1.1"
install.go:176: [debug] CHART PATH: /home/aboje/.cache/helm/repository/pure-pso-6.1.1.tgz

install.go:188: [debug] WARNING: This chart or one of its subcharts contains CRDs. Rendering may fail or contain inaccuracies.
Error: values don't meet the specifications of the schema(s) in the following chart(s):
pure-pso:
- clusterID: Does not match pattern '^[a-zA-Z0-9_]+$'

helm.go:84: [debug] values don't meet the specifications of the schema(s) in the following chart(s):
pure-pso:
- clusterID: Does not match pattern '^[a-zA-Z0-9_]+$'

**Comment by aboje** [comment]
Are we forced to use the old pure.namespace value (pure-csi for us) so that PSO can manage volumes created by PSO5?

**Comment by dingyin** [comment]
In PSO 6, only alpha-numeric characters are allowed in the clusterID field. The same field in PSO 5 values.yaml is called “namespace”. This issue is known in the upgrading document from PSO 5 to 6.x: [https://github.com/purestorage/pso-csi/blob/master/docs/csi-5to6-upgradepath.md](https://github.com/purestorage/pso-csi/blob/master/docs/csi-5to6-upgradepath.md). 

> ⚠️ Certain restrictions were imposed on PSO 6 clusterID (Only alphanumeric and underscores characters [maximum length 22]) and if your PSO 5.x namespace setting does not meet these restrictions, this upgrade tool will not work."

So we suggest to install 6 first and then import the volumes created by PSO 5 as follows: [https://github.com/purestorage/pso-csi/blob/master/docs/csi-volume-import.md](https://github.com/purestorage/pso-csi/blob/master/docs/csi-volume-import.md)

**Comment by aboje** [comment]
So the steps are to remove PSO5, install PSO6 (with a different clusterID value), then run imports for every persistent volume that was created by PSO5? 

I hate to ask, but why not just include the same character restrictions in the new clusterID field as you allowed in the namespace field?

**Comment by aboje** [comment]
If I am using a completely different clusterId/namespace value than I had in PSO5, should I keep the helm "upgrade" option to true?

**Comment by david-enli** [comment]
no, if you are freshly installing PSO6, you can omit the "upgrade" field or set it to false, setting it to true will fail the upgrade then fail the install. 
As for the reason that we impose new restrictions for PSO 6 clusterID, cockroach DB for PSO 6 requires no hyphen in our implementation. Apologize for the inconvenience.
