### ISSUE TITLE
Upgrade to pure-pso 6.2.2 Cockroach stays on old version

### ISSUE THREAD

**Issue by eRaid6** [purestorage/pso-csi#206]
I just upgraded pure-pso to 6.2.2 following the directions at https://github.com/purestorage/pso-csi/tree/master/pure-pso#upgrading-within-major-verstion and the `pso-db-X-X` pods did not restart, and are still on the old version.  All other pods restarted and are on the new version.  I manually restarted `pso-db-0-0` to see if it would restart on the new version of Cockroach, but it did not.

```
> oc get pods
NAME                                        READY   STATUS    RESTARTS   AGE
pso-csi-controller-0                        6/6     Running   0          16m
pso-csi-node-fm9vm                          3/3     Running   0          16m
pso-csi-node-nkzr9                          3/3     Running   0          16m
pso-csi-node-xfqpt                          3/3     Running   0          16m
pso-db-0-0                                  1/1     Running   0          3m40s
pso-db-1-0                                  1/1     Running   3          11d
pso-db-2-0                                  1/1     Running   4          11d
pso-db-3-0                                  1/1     Running   8          11d
pso-db-4-0                                  1/1     Running   4          11d
pso-db-cockroach-operator-c6d74786c-pmx9c   1/1     Running   0          16m
pso-db-deployer-64577468d6-2q26h            1/1     Running   0          16m
```

Any help or direction would be greatly appreciated.

**Comment by haibinxie** [comment]
Unfortunately we dont support cockroach DB upgrade, cockroach has complicated upgrade instructions, the steps change when upgrading to different version. please change the cockroach db version back to the original version, even we see old version is still used, if any pod is down due to infrastructure issue, we will create new pod to replace it and new pod will use new version, which may result in unknown behavior due to mismatched version in db pods.

here is cockroach db upgrade instruction, choose the destination version to see the instruciton https://www.cockroachlabs.com/docs/v21.1/upgrade-cockroach-version

**Comment by pure-jliao** [comment]
closing if no further questions.
